name: walls
version: 0.1.0.0
ghc-options:
  -Wall -threaded -rtsopts -with-rtsopts=-N -with-rtsopts=-A128m -with-rtsopts=-n8m
dependencies:
  - aeson
  - ansi-terminal
  - base
  - base-prelude
  - bytestring
  - containers
  - interpolate
  - lens
  - lifted-base
  - servant
  - servant-server
  - template-haskell
  - text
  - wai
  - warp
  - wreq
default-extensions:
  - DataKinds
  - FlexibleContexts
  - FunctionalDependencies
  - GADTs
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeFamilies
  - TypeOperators
executables:
  walls:
    main: Main.hs
    source-dirs: src/
