flags:
  time-locale-compat:
    old-locale: false
ghc-options:
  walls: -W -Werror -threaded -rtsopts -with-rtsopts=-N -with-rtsopts=-A512m -with-rtsopts=-n8m
    -with-rtsopts=-gq
setup-info:
  ghc:
    windows64:
      8.2.0.20170704:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc3/ghc-8.2.0.20170704-x86_64-unknown-mingw32.tar.xz
        sha1: 3648302c66769d4aa0c3a9f82be4538f402f234f
        content-length: 175463160
    linux64:
      8.2.0.20170704:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc3/ghc-8.2.0.20170704-x86_64-deb8-linux.tar.xz
        sha1: ac1598c21ea2936b091885a29a0f5725668aaed5
        content-length: 138482820
    macosx:
      8.2.0.20170704:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc3/ghc-8.2.0.20170704-x86_64-apple-darwin.tar.xz
        sha1: 81e3093b559b9aaf8af2a89f182539849539cbe1
        content-length: 125197252
extra-deps:
- RSA-2.3.0
- SHA-1.6.4.2
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-1.2.1.0
- aeson-pretty-0.8.5
- ansi-terminal-0.6.3.1
- ansi-wl-pprint-0.6.7.3
- appar-0.1.4
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.1.1
- attoparsec-0.13.1.0
- attoparsec-iso8601-1.0.0.0
- authenticate-oauth-1.6
- auto-update-0.1.4
- base-compat-0.9.3
- base-orphans-0.6
- base-prelude-1.2.0.1
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- bifunctors-5.4.2
- blaze-builder-0.4.0.2
- blaze-html-0.9.0.1
- blaze-markup-0.8.0.0
- byteable-0.1.1
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- case-insensitive-1.2.0.10
- cereal-0.5.4.0
- cmdargs-0.10.17
- comonad-5.0.1
- connection-0.2.8
- contravariant-1.4
- cookie-0.4.2.1
- cpphs-1.20.8
- crypto-api-0.13.2
- crypto-pubkey-types-0.4.3
- cryptohash-0.11.9
- cryptonite-0.24
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- distributive-0.5.2
- dlist-0.8.0.3
- easy-file-0.2.1
- entropy-0.3.8
- exceptions-0.8.3
- fail-4.9.0.0
- fast-logger-2.4.10
- file-embed-0.0.10
- foundation-0.0.13
- free-4.12.4
- hashable-1.2.6.1
- haskell-src-exts-1.19.1
- haskell-src-meta-0.8.0.1
- hex-0.1.2
- hourglass-0.2.10
- http-api-data-0.3.7.1
- http-client-0.5.7.0
- http-client-tls-0.3.5.1
- http-date-0.0.6.1
- http-media-0.7.0
- http-types-0.9.1
- http2-1.6.3
- integer-logarithms-1.0.2
- interpolate-0.1.1
- iproute-1.7.1
- kan-extensions-5.0.2
- lens-4.15.3
- lens-aeson-1.0.1
- lifted-base-0.2.3.11
- memory-0.14.6
- mime-types-0.1.0.7
- mmorph-1.1.0
- monad-control-1.0.2.1
- mtl-2.2.1
- natural-transformation-0.4
- network-2.6.3.2
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.14.0.0
- parallel-3.2.1.1
- parsec-3.1.11
- pem-0.2.2
- polyparse-1.12
- prelude-extras-0.4.0.3
- primitive-0.6.2.0
- profunctors-5.2
- psqueues-0.2.3.0
- random-1.1
- reflection-2.1.2
- resourcet-1.1.9
- safe-0.3.15
- scientific-0.3.5.1
- semigroupoids-5.2
- semigroups-0.18.3
- servant-0.11
- servant-server-0.11
- simple-sendfile-0.2.25
- socks-0.5.5
- split-0.2.3.2
- stm-2.4.4.1
- streaming-commons-0.1.18
- string-conversions-0.4.0.1
- stringsearch-0.3.6.6
- syb-0.7
- system-filepath-0.4.13.4
- tagged-0.8.5
- text-1.2.2.2
- th-abstraction-0.2.3.0
- th-expand-syns-0.4.3.0
- th-lift-0.7.7
- th-lift-instances-0.1.11
- th-orphans-0.13.3
- th-reify-many-0.1.7
- time-locale-compat-0.1.1.3
- tls-1.3.11
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.3.1
- unix-time-0.3.7
- unordered-containers-0.2.8.0
- uri-bytestring-0.2.3.3
- utf8-string-1.0.1.1
- uuid-types-1.0.3
- vault-0.3.0.7
- vector-0.12.0.1
- void-0.7.2
- wai-3.2.1.1
- wai-app-static-3.1.6.1
- wai-extra-3.0.20.0
- wai-logger-2.3.0
- warp-3.2.13
- word8-0.1.2
- x509-1.6.5
- x509-store-1.6.2
- x509-system-1.6.4
- x509-validation-1.6.5
- zlib-0.6.1.2
- cabal-doctest-1.0.2
- wreq-0.5.0.2
compiler-check: match-exact
compiler: ghc-8.2.0.20170704
resolver: ghc-8.2.0.20170704
packages:
  - "."
  - location:
      git: /Users/h/m/scratch/wreq
      commit: 6c126329d756674971336bd5f2d53e642a061c9a
    extra-dep: true
